"""order rels on delete append

Revision ID: a83db4070aa9
Revises: 98cb51802bb1
Create Date: 2025-12-10 14:42:25.595517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a83db4070aa9'
down_revision: Union[str, Sequence[str], None] = '98cb51802bb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('order_product_association_order_id_fkey'), 'order_product_association', type_='foreignkey')
    op.create_foreign_key(None, 'order_product_association', 'orders', ['order_id'], ['id'], ondelete='cascade')
    op.drop_constraint(op.f('order_product_materials_order_product_id_fkey'), 'order_product_materials', type_='foreignkey')
    op.create_foreign_key(None, 'order_product_materials', 'order_product_association', ['order_product_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_product_materials', type_='foreignkey')
    op.create_foreign_key(op.f('order_product_materials_order_product_id_fkey'), 'order_product_materials', 'order_product_association', ['order_product_id'], ['id'])
    op.drop_constraint(None, 'order_product_association', type_='foreignkey')
    op.create_foreign_key(op.f('order_product_association_order_id_fkey'), 'order_product_association', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###
