"""independed deletes

Revision ID: c49751ab8e56
Revises: a83db4070aa9
Create Date: 2025-12-17 13:32:26.773280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c49751ab8e56'
down_revision: Union[str, Sequence[str], None] = 'a83db4070aa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_product_association', 'product_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('idx_unique_order_product'), 'order_product_association', type_='unique')
    op.alter_column('order_product_materials', 'material_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('idx_unique_order_product_material'), 'order_product_materials', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('idx_unique_order_product_material'), 'order_product_materials', ['order_product_id', 'material_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('order_product_materials', 'material_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(op.f('idx_unique_order_product'), 'order_product_association', ['order_id', 'product_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('order_product_association', 'product_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
