"""append cascade deleta for table order_product_material when material deleted

Revision ID: d352022f98cc
Revises: c49751ab8e56
Create Date: 2025-12-17 15:14:12.359887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd352022f98cc'
down_revision: Union[str, Sequence[str], None] = 'c49751ab8e56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('order_product_materials_material_id_fkey'), 'order_product_materials', type_='foreignkey')
    op.create_foreign_key(None, 'order_product_materials', 'materials', ['material_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_product_materials', type_='foreignkey')
    op.create_foreign_key(op.f('order_product_materials_material_id_fkey'), 'order_product_materials', 'materials', ['material_id'], ['id'])
    # ### end Alembic commands ###
