"""start

Revision ID: e80846e2dfd4
Revises: 
Create Date: 2025-11-30 22:56:23.459380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e80846e2dfd4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_pw', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materials',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('material_type', sa.String(), nullable=False),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('pack_price', sa.Integer(), nullable=False),
    sa.Column('one_item_price', sa.Integer(), nullable=False),
    sa.Column('count_in_one_pack', sa.Integer(), nullable=False),
    sa.Column('count_left', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_pw', sa.LargeBinary(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('carts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Integer(), server_default='0', nullable=False),
    sa.Column('materials_price', sa.Integer(), server_default='0', nullable=False),
    sa.Column('customer', sa.String(), nullable=True),
    sa.Column('descriptions', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('hiring_date', sa.DateTime(), nullable=True),
    sa.Column('ready_date', sa.DateTime(), nullable=True),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.Column('canceled_date', sa.DateTime(), nullable=True),
    sa.Column('paid', sa.Integer(), server_default='0', nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_material_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('material_id', sa.String(), nullable=False),
    sa.Column('quantity_in_one_mat_unit', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'material_id', name='idx_unique_product_material')
    )
    op.create_table('product_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('start', sa.Integer(), nullable=False),
    sa.Column('end', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart_product_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('product_price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cart_id', 'product_id', name='idx_unique_cart_product')
    )
    op.create_table('order_product_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('product_price', sa.Integer(), server_default='0', nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'product_id', name='idx_unique_order_product')
    )
    op.create_table('order_product_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_product_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.String(), nullable=False),
    sa.Column('qty_prod_in_mat', sa.Integer(), server_default='0', nullable=False),
    sa.Column('budged_usage', sa.Integer(), server_default='0', nullable=False),
    sa.Column('actual_usage', sa.Integer(), server_default='0', nullable=False),
    sa.Column('material_price', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['order_product_id'], ['order_product_association.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_product_id', 'material_id', name='idx_unique_order_product_material')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_product_materials')
    op.drop_table('order_product_association')
    op.drop_table('cart_product_association')
    op.drop_table('product_prices')
    op.drop_table('product_material_association')
    op.drop_table('orders')
    op.drop_table('carts')
    op.drop_table('users')
    op.drop_table('products')
    op.drop_table('materials')
    op.drop_table('clients')
    # ### end Alembic commands ###
