"""append to expends table new column-periodicity 

Revision ID: ef59aafd5cb2
Revises: d6857dc5bf7f
Create Date: 2025-12-19 14:19:29.809596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef59aafd5cb2'
down_revision: Union[str, Sequence[str], None] = 'd6857dc5bf7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('periodicity', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'periodicity')
    # ### end Alembic commands ###
